name: docker build
on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"
permissions:
  packages: write
  contents: read
jobs:
  docker:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set variables useful for later
        id: useful_vars
        run: |-
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=schedule,suffix=-${{ matrix.platform }}
            type=ref,event=branch,suffix=-${{ matrix.platform }}
            type=ref,event=pr,suffix=-${{ matrix.platform }}
            type=semver,pattern={{version}},suffix=-${{ matrix.platform }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.platform }}
            type=semver,pattern={{major}},suffix=-${{ matrix.platform }}
            type=sha,prefix=,format=long,event=tag,suffix=-${{ matrix.platform }}
            type=sha,suffix=-${{ matrix.platform }}
            type=raw,value=latest-${{ matrix.platform }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=${{ github.ref_name }}-${{ steps.useful_vars.outputs.short_sha }}-${{ steps.useful_vars.outputs.timestamp }}-${{ matrix.platform }},enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: |
            suffix=-{{arch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.runner }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ matrix.runner }}-buildx-
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          build-args: |
            GIT_COMMIT=${{ github.sha }}
